name: Deploy MELANO INC

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Lint code
        run: flake8 .

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/melano-inc:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/melano-inc:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/melano-inc:latest
            docker stop melano-inc || true
            docker rm melano-inc || true
            docker run -d --name melano-inc -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/melano-inc:latest

      - name: Notify Slack (via Chronos)
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"🚀 MELANO INC desplegado correctamente."}' ${{ secrets.SLACK_WEBHOOK_URL }}
